1426 average grade improvement
TUM-Dev/Campus-Android pull request #1439
Opened 2022-05-08 17:58 UTC by tobiasjungmann

## Issue
This is an early draft to improve the average grade as it was described in Issue [1246](https://github.com/TUM-Dev/Campus-Android/issues/1426). Users can enter their own values for a weight and the credits for a course in a separate edit mode.

## Changes
### UI
I added an edit mode which can be activated with a gear icon in the menu bar. With the edit mode switched off, the UI is unchanged. The number of credits and the courses weight can be entered for every exam individually.
Hiding a grade removes the grade color from the `TextView` on the right and deactivates `EditTexts`.
<img src="https://user-images.githubusercontent.com/32565407/167308785-3ad92dc2-cc1a-4200-a181-a5c2a61727f1.png" data-canonical-src="https://user-images.githubusercontent.com/32565407/167308785-3ad92dc2-cc1a-4200-a181-a5c2a61727f1.png" width="280" height="400" />

### Logic
A json String of all exam objects (the grades) is now saved in the shared preferences. This string is used to load the list of exams instead of the previously used cache.
Changes for each grade are stored directly in the shared preferences and are handled by the method `storeExamListInSharedPreferences`. At the moment the list is stored after each change, but this will be changed until the the PR is finalized in order to improve performance. `loadExamListFromSharedPreferences` Loads the stored exam object from the shared preferences. Additionally, a third important method `addAllNewItemsToExamList` adds all new grades to the list of exams and initializes them with their default values. 

## Still to do
- [ ] Improve `RecyclerView` performance
- [ ] Improve performance - reduce the amount of accesses to the shared preferences significantly
- [ ] Add and remove custom exams.
- [ ] Update the `GradeBackgroundUpdater` so that it also works on the stored json string.
- [ ] Update diagrams to represent the weights and different amounts of credits.
- [ ] Update the average grade.

Any ideas for improvement are very welcome!

2022-07-14 08:57 UTC, tobiasjungmann commented
The rebase was more or less successful. Now the branch can be merged into the master again without conflicts.

2022-07-20 06:40 UTC, tobiasjungmann commented
Thank you for your review, the questionmark is now fixed.

2022-07-27 19:45 UTC, COM8 requested changes

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +            ) {
Use `[X]` instead of `get(X)` or a regex

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +            ) {
https://regex101.com/

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +            if (weight < 0.0) {             //weight sanitization
```suggestion
            if (weight < 0.0) { // weight sanitization
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +        val scale = resources.displayMetrics.density
```suggestion
        val density = resources.displayMetrics.density
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +            param.setMargins(0, ((32 * scale + 0.5f).toInt()), 0, 0)
```suggestion
            param.setMargins(0, ((32 * density + 0.5f).toInt()), 0, 0)
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +            param.setMargins(0, ((32 * scale + 0.5f).toInt()), 0, 0)
And please add a comment, why this is required.

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +            binding.gradesListView.setPadding(0, ((256 * scale + 0.5f).toInt()), 0, 0)
```suggestion
            binding.gradesListView.setPadding(0, ((256 * density + 0.5f).toInt()), 0, 0)
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/model/Exam.kt
> +    @PropertyElement(name = "subjectcredits")               //must not be "credits" -> otherwise naming collision will occur
```suggestion
    // must not be "credits" -> otherwise naming collision will occur
    @PropertyElement(name = "subjectcredits")
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/model/Exam.kt
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout-land/fragment_grades.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
```suggestion
</androidx.constraintlayout.widget.ConstraintLayout>

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/activity_grades_listview.xml
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/activity_grades_listview.xml
> +
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/activity_grades_listview.xml
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/activity_grades_listview.xml
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/activity_grades_listview.xml
> +
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/activity_grades_listview.xml
> +
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/activity_grades_listview.xml
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/dialog_add_grade_input.xml
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/dialog_add_grade_input.xml
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/dialog_add_grade_input.xml
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/dialog_add_grade_input.xml
> +
```suggestion
        </LinearLayout>
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
> +
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
> +
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
> +
```suggestion

```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
> +
```suggestion
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/layout/fragment_grades.xml
> +
```suggestion
                    android:visibility="visible" />
```

2022-07-27 19:45 UTC, COM8 commented on app/src/main/res/menu/menu_activity_grades.xml
> +
```suggestion

```

2022-07-28 10:08 UTC, COM8 approved these changes

2022-07-28 12:39 UTC, COM8 approved these changes

2022-07-28 12:45 UTC, Bentipa approved these changes
Feature wise approved, @COM8 did the code review so fine to go

2022-07-28 12:51 UTC, merged