Bugfix/grades bar chart
TUM-Dev/Campus-Android pull request #1506
Opened 2022-07-31 09:54 UTC by tobiasjungmann

This PR addresses the [issue](https://github.com/TUM-Dev/Campus-Android/issues/1505) for the grade diagram styling.

Now, the y-axis is removed if weights are used in the diagram.
Additionally, the x-axis now shows the grades instead of "some" numbers and there is a small description for exams whch are marked as passed.

Chart diagram with weights:
<img src="https://user-images.githubusercontent.com/32565407/182020689-889ae279-dd1f-4612-b0c8-29fbf22f78b6.jpg" data-canonical-src="https://user-images.githubusercontent.com/32565407/182020689-889ae279-dd1f-4612-b0c8-29fbf22f78b6.jpg"  width="270" height="585" />

Chart diagram without weights:
<img src="https://user-images.githubusercontent.com/32565407/182020695-fc1be116-5732-42f2-a80c-af1cf40e0a6d.jpg" data-canonical-src="https://user-images.githubusercontent.com/32565407/182020695-fc1be116-5732-42f2-a80c-af1cf40e0a6d.jpg" width="270" height="585"/>

Since most phone screens are to small to display the values on top of the individual bars, I have replace them with horizontal lines to the y-axis.
Additionally, the button to toggle between the diagrams is not shown in the edit mode anymore.

2022-07-31 10:31 UTC, Bentipa requested changes
In addition to the code comments one question.
Why don't you show y-axis makers in the normal view (with weights)?
So previously you can see how many ects per grade you have right? 
Now you can not see it at all anymore?
And what is directly the difference between the diagrams "with" and "without weights"?


PS: I guess you mean bar and not chart diagram.

2022-07-31 10:31 UTC, Bentipa commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +                // description = null
remove comment

2022-07-31 10:31 UTC, Bentipa commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +
```suggestion
```

2022-07-31 10:31 UTC, Bentipa commented on app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesFragment.kt
> +            pieMenuItem?.isVisible = !(binding.barChartView.visibility == View.GONE)
```suggestion
            pieMenuItem?.isVisible = binding.barChartView.visibility != View.GONE
```

2022-07-31 10:31 UTC, Bentipa commented on app/src/main/res/values/strings.xml
> +    <string name="grade_passed_annotation">Exam Passed Without a Grade</string>
```suggestion
    <string name="grade_passed_annotation">Exam passed without a grade</string>
```

2022-07-31 12:47 UTC, tobiasjungmann commented
Yes, I mean the bar-chart. The bar chart shows not only ects*grade but also includes a weight (e.g. PGDP has 6 ects and a weight of 0.5). Therefore, the y axis wouldn't directly translate to credits, but more as a general relation between them. The version "without weights" only counts exams with this grade, the version with weights computes weight*ects*grade.

2022-08-01 14:27 UTC, Bentipa commented
I am wondering what benefit this visualization this would now have for a user.
He knows then that in relation his 1.0 grades might count less than some 2.0 grades right?

For me it's hard to interpret that without knowing what is shown in the diagram at all.
So either we add some explanation why it's useful or we make it more simple (e.g., just showing the amount of grades per grade again). But maybe someone else has another opinion on that? @CommanderStorm

2022-08-01 16:22 UTC, tobiasjungmann commented
Yes, it would only show the relation you described, without any real correlation. One idea that came to my mind would be to show percentages on the y axis in this case to visualize the proportion of one grade (with weighting) from the total set of grades and weightings. Then we would have a meaningful(lish) label for the diagram.

2022-08-06 14:56 UTC, CommanderStorm commented
> But maybe someone else has another opinion on that? @CommanderStorm

I will review this once my exams are done next week.

2022-09-28 17:05 UTC, CommanderStorm commented
This branch crashes on my device. Can you reproduce this?

2022-10-01 08:31 UTC, tobiasjungmann commented
The crash was connected to inconsistent database version from switching between this branch and the chat removal. You have to manually uninstall the app. Before relaunching the version from the other branch. Depending on whether the chat removal PR gets merged soon, this can be merged afterwards or directly without the rebasing commits.

2022-10-10 08:33 UTC, CommanderStorm commented
@tobiasjungmann sorry for the long delay on this one. Could you rebase onto main? 😅

2022-11-03 20:35 UTC, tobiasjungmann commented
Its finally rebased and manageable small again. Looking for your code reviews again!

2022-11-04 09:21 UTC, kordianbruck approved these changes

2022-11-04 09:21 UTC, merged

2022-11-04 11:43 UTC, kordianbruck commented
Awesome, thanks so much!